apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-dev
  namespace: argocd
  labels:
    env: dev
    app: vault
spec:
  project: hashicorp-vault
  sources:
    # 1. Vendored Vault Helm chart with dev values
    - repoURL: https://github.com/medalizaidi/vault
      targetRevision: main
      path: charts/vault
      helm:
        releaseName: vault
        valueFiles:
          - values.yaml
          - ../../envs/values-dev.yaml


  destination:
    server: https://kubernetes.default.svc  
    namespace: vault

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
